import { jsPDF } from 'jspdf';
import { reportError } from '@/lib/rollbar-utils';
import { SoapNote } from '@/types/soap-note';

export const exportService = {
    async exportTranscriptAsText(transcript: string, filename: string) {
        try {
            const blob = new Blob([transcript], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${filename}.txt`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            return true;
        } catch (error) {
            reportError(error, 'exportTranscriptAsText');
            return false;
        }
    },

    async exportSoapNoteAsPDF(soapNote: SoapNote, patientName: string, date: string) {
        try {
            const doc = new jsPDF();

            // Header
            doc.setFontSize(20);
            doc.text('SOAP Note', 20, 20);

            doc.setFontSize(12);
            doc.text(`Patient: ${patientName}`, 20, 35);
            doc.text(`Date: ${date}`, 20, 42);
            doc.text(`Status: ${soapNote.is_finalized ? 'Finalized' : 'Draft'}`, 20, 49);

            let y = 65;
            const sections = [
                { title: 'Subjective', content: soapNote.subjective },
                { title: 'Objective', content: soapNote.objective },
                { title: 'Assessment', content: soapNote.assessment },
                { title: 'Plan', content: soapNote.plan }
            ];

            sections.forEach(section => {
                // Section Title
                doc.setFontSize(14);
                doc.setFont('helvetica', 'bold');
                doc.text(section.title, 20, y);
                y += 10;

                // Section Content
                doc.setFontSize(12);
                doc.setFont('helvetica', 'normal');

                const splitText = doc.splitTextToSize(section.content, 170);
                doc.text(splitText, 20, y);

                y += (splitText.length * 7) + 10;

                // New page if needed
                if (y > 270) {
                    doc.addPage();
                    y = 20;
                }
            });

            // Footer
            const pageCount = doc.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(10);
                doc.text(`Page ${i} of ${pageCount}`, 180, 290);
                doc.text('Generated by SafeSpace AI Scribe', 20, 290);
            }

            doc.save(`SOAP_Note_${patientName}_${date}.pdf`);
            return true;
        } catch (error) {
            reportError(error, 'exportSoapNoteAsPDF');
            return false;
        }
    },

    async copyToClipboard(text: string) {
        try {
            await navigator.clipboard.writeText(text);
            return true;
        } catch (error) {
            reportError(error, 'copyToClipboard');
            return false;
        }
    }
};
