import { useState, useCallback } from 'react';
import * as recordingService from '../../../api/recordingService';

export const useSoapNote = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [soapNote, setSoapNote] = useState<any | null>(null);
  const [error, setError] = useState<string | null>(null);

  const generateSoapNote = useCallback(async (transcriptId: string, appointmentId: string) => {
    try {
      setIsGenerating(true);
      setError(null);

      // PLACEHOLDER: Simulate SOAP note generation
      console.log('PLACEHOLDER: SOAP note would be generated for transcript:', transcriptId);

      // Simulate processing delay
      await new Promise(resolve => setTimeout(resolve, 3000));

      const mockSoapNote = {
        id: `soap_${Date.now()}`,
        transcript_id: transcriptId,
        appointment_id: appointmentId,
        subjective: 'Placeholder subjective section. This will be generated by GPT-4o after backend configuration.',
        objective: 'Placeholder objective section. This will contain therapist observations.',
        assessment: 'Placeholder assessment section. This will contain clinical analysis.',
        plan: 'Placeholder plan section. This will contain treatment recommendations.',
        is_finalized: false,
        edited_by_mentor: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };

      setSoapNote(mockSoapNote);
      setIsGenerating(false);

      return mockSoapNote;
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      setError(message);
      setIsGenerating(false);
      return null;
    }
  }, []);

  const updateSoapNote = useCallback(async (soapNoteId: string, updates: any) => {
    try {
      const updated = await recordingService.updateSoapNote(soapNoteId, updates);
      if (updated) {
        setSoapNote(updated);
      }
      return updated;
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      setError(message);
      return null;
    }
  }, []);

  const finalizeSoapNote = useCallback(async (soapNoteId: string) => {
    try {
      const success = await recordingService.finalizeSoapNote(soapNoteId);
      if (success && soapNote) {
        setSoapNote({ ...soapNote, is_finalized: true });
      }
      return success;
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      setError(message);
      return false;
    }
  }, [soapNote]);

  return {
    generateSoapNote,
    updateSoapNote,
    finalizeSoapNote,
    soapNote,
    isGenerating,
    error,
  };
};
